[tool.poetry]
name = "mathieu-lemay-cv"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
rendercv = "^1.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
